# preprocessing
base_config:
  - configs/base_hifi.yaml

data_input_path: [wav]
data_out_path: [out]
val_num: 2
return_type: "mel+linear"

pe: 'parselmouth' # 'parselmouth' or 'harvest'
f0_min: 65
f0_max: 1100

aug_min: 0.9
aug_max: 1.4
aug_num: 1
key_aug: false
key_aug_prob: 0.5

pc_aug: true # pc-nsf training method
pc_aug_rate: 0.4
pc_aug_key: 12

use_stftloss: false
loss_fft_sizes: [2048, 2048, 4096, 1024, 512, 256, 128,1024, 2048, 512]
loss_hop_sizes: [512, 240, 480, 100, 50, 25, 12,120, 240, 50]
loss_win_lengths: [2048, 1200, 2400, 480, 240, 120, 60,600, 1200, 240]

use_RSSloss: true
RSS_fft_min: 256
RSS_fft_max: 2048
RSS_n_scale: 4

kl_loss_weight: 0.000001

lab_aux_melloss: 4
lab_aux_stftloss: 15

raw_data_dir: []
binary_data_dir: null
binarization_args:
  num_workers: 8
  shuffle: true

DataIndexPath: data
valid_set_name: valid
train_set_name: train


volume_aug: true
volume_aug_prob: 0.5


mel_vmin: -14. #-6.
mel_vmax: 4.


audio_sample_rate: 44100
audio_num_mel_bins: 128
hop_size: 512            # Hop size.
fft_size: 2048           # FFT size.
win_size: 2048           # FFT size.
fmin: 40
fmax: 16000
fmax_for_loss: null
crop_mel_frames: 32



# global constants


# neural networks


#model_cls: training.nsf_HiFigan_task.nsf_HiFigan
g_model_args:
  mini_nsf: true
  noise_sigma: 0.05
  upsample_rates: [ 8, 8, 2, 2, 2 ]
  upsample_kernel_sizes: [ 16,16, 4, 4, 4 ]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [ 3,7,11 ]
  resblock_dilation_sizes: [ [ 1,3,5 ], [ 1,3,5 ], [ 1,3,5 ] ]
  discriminator_periods: [ 3, 5, 7, 11, 17, 23, 37 ]
  resblock: "1"

e_model_args:
  inter_channels: 128    # 和mel_channels一样
  resblock: "2"
  resblock_kernel_sizes: [3,5]
  resblock_dilation_sizes: [[3,5],[3,5]]
  downsample_rates: [1,1]
  downsample_kernel_sizes: [5,5]
  downsample_channels: [1025,512,256]

# training

task_cls: training.spec_nsf_HiFivae_task.spec_nsf_HiFivae


#sort_by_len: true
#optimizer_args:
#  optimizer_cls: torch.optim.AdamW
#  lr: 0.0001
#  beta1: 0.9
#  beta2: 0.98
#  weight_decay: 0
#lab_aux_loss: 0.5
discriminate_optimizer_args:
  optimizer_cls: torch.optim.AdamW
  lr: 0.00001
  beta1: 0.8
  beta2: 0.99
  weight_decay: 0

generater_optimizer_args:
  optimizer_cls: torch.optim.AdamW
  lr: 0.00001
  beta1: 0.8
  beta2: 0.99
  weight_decay: 0

lr_scheduler_args:
  scheduler_cls: lr_scheduler.scheduler.WarmupLR
  warmup_steps: 5000
  min_lr: 0.00001

clip_grad_norm: 1
accumulate_grad_batches: 1
sampler_frame_count_grid: 6
ds_workers: 4
dataloader_prefetch_factor: 2

batch_size: 2



num_valid_plots: 100
log_interval: 100
num_sanity_val_steps: 2  # steps of validation at the beginning
val_check_interval: 2000
num_ckpt_keep: 5
max_updates: 100000
permanent_ckpt_start: 200000
permanent_ckpt_interval: 40000

###########
# pytorch lightning
# Read https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api for possible values
###########
pl_trainer_accelerator: 'auto'
pl_trainer_devices: 'auto'
pl_trainer_precision: '32-true'
#pl_trainer_precision: 'bf16' #please do not use bf 16
pl_trainer_num_nodes: 1
pl_trainer_strategy: 
  name: auto
  process_group_backend: nccl
  find_unused_parameters: true
nccl_p2p: true
seed: 114514

###########
# finetune
###########

finetune_enabled: true
finetune_ckpt_path: pc_nsf_hifigan_44.1k_hop512_128bin_2025.02.ckpt
encoder_ckpt_path: "experiments/mrl_encoder1/model_ckpt_steps_18000.ckpt"
finetune_ignored_params: []
finetune_strict_shapes: true

freezing_enabled: false
frozen_params: []
